import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { initStoryblok } from "./lib/storyblok";
import Header from "./components/Header";
import Footer from "./components/Footer";

initStoryblok();


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div style={{ maxWidth: 980, margin: "0 auto", padding: "0 20px" }}>
          <Header />
          <main style={{ paddingTop: 28 }}>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
